app/main/models/setting.py
from ... import db


class NetworkSettingEnum(db.Enum):
	network_segment = 'network_segment'
	network_card = 'network_card'


class NetworkTypeEnum(db.Enum):
	intranet = 'intranet'
	extranet = 'extranet'


class Network(db.Model):
	id = db.Column(db.Integer, primary_key=True, nullable=False)
	intranet_segment = db.Column(db.String(80), nullable=False)
	extranet_segment = db.Column(db.String(80), nullable=False)
	intranet_card = db.Column(db.String(80), nullable=False)
	extranet_card = db.Column(db.String(80), nullable=False)

	def __init__(self, intranet_segment, extranet_segment, intranet_card, extranet_card):
		self.intranet_segment = intranet_segment
		self.extranet_segment = extranet_segment
		self.intranet_card = intranet_card
		self.extranet_card = extranet_card


class Backup(db.Model):
	id = db.Column(db.Integer, primary_key=True, nullable=False)
	step = db.Column(db.Integer, nullable=False)

	def __init__(self, step):
		self.step = step


class Upgrade(db.Model):
	id = db.Column(db.Integer, primary_key=True, nullable=False)
	rule_upload_address = db.Column(db.String(80), nullable=False)
	rule_upgrade_time = db.Column(db.Time, nullable=False)
	threat_upload_address = db.Column(db.String(80), nullable=False)
	threat_upgrade_time = db.Column(db.Time, nullable=False)

	def __init__(self, rule_upload_address, rule_upgrade_time, threat_upload_address, threat_upgrade_time):
		self.rule_upload_address = rule_upload_address
		self.rule_upgrade_time = rule_upgrade_time
		self.threat_upload_address = threat_upload_address
		self.threat_upgrade_time = threat_upgrade_time


class Warning(db.Model):
	id = db.Column(db.Integer, primary_key=True, nullable=False)
	level = db.Column(db.Integer, nullable=False)
	title = db.Column(db.String(80), nullable=False)

	def __init__(self, level, title):
		self.level = level
		self.title = title


class WarningEmail(db.Model):
	id = db.Column(db.Integer, primary_key=True, nullable=False)
	email = db.Column(db.String(80), nullable=False)

	def __init__(self, email):
		self.email = email

app/main/views/setting.py
import psutil
import re
import os

from flask import (
	current_app, Blueprint, flash, redirect, render_template, request, jsonify, url_for
)

from ..models.setting import Backup, Network, Upgrade, Warning, WarningEmail
from ... import db
from .auth import login_required
from dateutil import parser
from datetime import datetime

bp = Blueprint('setting', __name__, url_prefix='/setting')


def update_file(file_path, search_pattern, replace_pattern, replace_data):
	file_data = list()

	with open(file_path, "r", encoding="utf-8") as file:
		for line in file:
			regex = re.compile(search_pattern)
			result = regex.search(line)
			if result is not None:
				file_data.append(re.sub(replace_pattern, replace_data, line))
			else:
				file_data.append(line)

	with open(file_path, 'w', encoding='utf-8') as file:
		file.write(''.join(file_data))


def update_ip_file(file_path, ip):
	search_pattern = 'IP=(.*)'
	replace_pattern = '=(.*)'
	replace_data = '={IP}'.format(IP=ip)

	update_file(file_path, search_pattern, replace_pattern, replace_data)


def update_ruleupdate_file(ip):
	file_path = current_app.config.get('RULE_UPDATE_FILE')

	update_ip_file(file_path, ip)


def update_logupload_file(ip):
	file_path = current_app.config.get('LOG_UPLOAD_FILE')

	update_ip_file(file_path, ip)


def update_crontab_file(logupload_time, ruleupdate_time):
	file_path = current_app.config.get('CRONTAB_FILE')

	search_pattern = '(.*)/logupload'
	replace_pattern = '(\s{2})(\d+)(\s{2})(\d+)(\s{2})'
	time_list = logupload_time.split(':')
	replace_data = '  {minute}  {hour}  '.format(minute=int(time_list[1]), hour=int(time_list[0]))
	update_file(file_path, search_pattern, replace_pattern, replace_data)

	search_pattern = '(.*)/ruleupdate'
	replace_pattern = '(\s{2})(\d+)(\s{2})(\d+)(\s{2})'
	time_list = ruleupdate_time.split(':')
	replace_data = '  {minute}  {hour}  '.format(minute=int(time_list[1]), hour=int(time_list[0]))
	update_file(file_path, search_pattern, replace_pattern, replace_data)


def update_warning_file(level):
	file_path = current_app.config.get('BIGEYE_CFG_FILE')
	search_pattern = 'alertlevel = (\d+)'
	replace_pattern = '(\d+)'
	replace_data = level

	update_file(file_path, search_pattern, replace_pattern, replace_data)


def save_warning(warning_setting, request):
	if request.method == 'POST':
		level = request.form['level']
		title = request.form['title']

		error = None
		if not level:
			error = 'level is required.'
		elif not title:
			error = 'title is required.'

		if error is None:
			if warning_setting is not None:
				warning_setting.level = level
				warning_setting.title = title
			else:
				warning_setting = Warning(level, title)
				db.session.add(warning_setting)

			db.session.commit()
			update_warning_file(level)

		flash(error)

	return warning_setting


def save_upgrade(upgrade_setting, request):
	if request.method == 'POST':
		rule_upload_address = request.form['rule_upload_address']
		rule_upgrade_time = request.form['rule_upgrade_time']
		threat_upload_address = request.form['threat_upload_address']
		threat_upgrade_time = request.form['threat_upgrade_time']

		error = None
		if not rule_upload_address:
			error = 'rule upload address is required.'
		elif not rule_upgrade_time:
			error = 'rule upgrade time is required.'
		elif not threat_upload_address:
			error = 'threat upload address is required.'
		elif not threat_upgrade_time:
			error = 'threat upgrade time is required.'

		if error is None:
			if upgrade_setting is not None:
				upgrade_setting.rule_upload_address = rule_upload_address
				upgrade_setting.rule_upgrade_time = rule_upgrade_time
				upgrade_setting.threat_upload_address = threat_upload_address
				upgrade_setting.threat_upgrade_time = threat_upgrade_time
			else:
				upgrade_setting = Upgrade(rule_upload_address, rule_upgrade_time, threat_upload_address,
				                          threat_upgrade_time)
				db.session.add(upgrade_setting)

			db.session.commit()
			update_logupload_file(threat_upload_address)
			update_ruleupdate_file(rule_upload_address)
			update_crontab_file(threat_upgrade_time, rule_upgrade_time)

		flash(error)

	return upgrade_setting


@bp.route('/backup')
@login_required
def backup():
	backup_setting = Backup.query.first()
	return render_template('setting/backup.html', backup_setting=backup_setting)


@bp.route('/backup/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update_backup(id):
	backup_setting = Backup.query.filter_by(id=id).first()

	if request.method == 'POST':
		step = request.form['step']

		error = None
		if not step:
			error = 'step is required.'

		if error is None:
			if backup_setting is not None:
				backup_setting.step = step
				db.session.commit()
			else:
				backup_setting = Backup(step)
				db.session.add(backup_setting)

		flash(error)

	return render_template('setting/backup.html', backup_setting=backup_setting)


@bp.route('/backup/create', methods=('GET', 'POST'))
@login_required
def create_backup():
	backup_setting = None

	if request.method == 'POST':
		step = request.form['step']

		error = None
		if not step:
			error = 'step is required.'

		if error is None:
			backup_setting = Backup(step)
			db.session.add(backup_setting)
			db.session.commit()

		flash(error)

	return render_template('setting/backup.html', backup_setting=backup_setting)


@bp.route('/network')
@login_required
def network():
	network_setting = Network.query.first()
	return render_template('setting/network.html', network_setting=network_setting)


def save_network(network_setting, request):
	if request.method == 'POST':
		intranet_segment = request.form['intranet_segment']
		extranet_segment = request.form['extranet_segment']
		intranet_card = request.form['intranet_card']
		extranet_card = request.form['extranet_card']

		error = None
		if not intranet_segment:
			error = 'intranet segment is required.'
		elif not extranet_segment:
			error = 'extranet segment is required.'
		elif not intranet_card:
			error = 'intranet card is required.'
		elif not extranet_card:
			error = 'extranet card is required.'

		if error is None:
			if network_setting is not None:
				network_setting.intranet_segment = intranet_segment
				network_setting.extranet_segment = extranet_segment
				network_setting.intranet_card = intranet_card
				network_setting.extranet_card = extranet_card
			else:
				network_setting = Network(intranet_segment, extranet_segment, intranet_card, extranet_card)
				db.session.add(network_setting)

			db.session.commit()

		flash(error)

	return network_setting


@bp.route('/network/create', methods=('GET', 'POST'))
@login_required
def create_network():
	network_setting = None

	network_setting = save_network(network_setting, request)

	return render_template('setting/network.html', network_setting=network_setting)


@bp.route('/network/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update_network(id):
	network_setting = Network.query.filter_by(id=id).first()

	network_setting = save_network(network_setting, request)

	return render_template('setting/network.html', network_setting=network_setting)


def get_process_started_time(proc_name):
	proc_run_days = None
	regex = re.compile("pid=(\d+),\sname=\'" + proc_name + "\',\sstarted=\'(.*)\'")

	for proc in psutil.process_iter():
		process_info = str(proc)
		result = regex.search(process_info)
		if result:
			proc_started_time = parser.parse(result.group(2))
			timedelta = datetime.now() - proc_started_time
			proc_run_days = round(timedelta.days + timedelta.seconds / 3600 / 24, 2)

			# minutes, hours = math.modf(timedelta.seconds / 3600)
			# minutes = int(round(minutes * 60))
			# if days:
			# 	proc_run_time = '{days}天 {hours}小时 {minutes}分钟 '.format(days=timedelta.days, hours=int(hours),
			#                                               minutes=int(minutes))
			# elif hours:
			# 	proc_run_time = '{hours}小时 {minutes}分钟 '.format(hours=int(hours),
			# 	                                minutes=int(minutes))
			# else:
			# 	proc_run_time = '{minutes}分钟 '.format(minutes=int(minutes))

			break

	return None


# return proc_run_days


@bp.route('/process', methods=('GET', 'POST'))
@login_required
def process():
	proc_run_time = {}

	extrannet_proc_name = current_app.config.get('EXTRANNET_PROC_NAME')
	extrannet_proc_run_time = get_process_started_time(extrannet_proc_name)
	proc_run_time.update(extrannet_proc_run_time=extrannet_proc_run_time)

	intrannet_proc_name = current_app.config.get('INTRANNET_PROC_NAME')
	intrannet_proc_run_time = get_process_started_time(intrannet_proc_name)
	proc_run_time.update(intrannet_proc_run_time=intrannet_proc_run_time)

	return render_template('setting/process.html', proc_run_time=proc_run_time)


@bp.route('/process/run', methods=('GET', 'POST'))
@login_required
def run_process():
	if request.method == 'POST':
		process_name = request.form['process_name']
		os.system(process_name)

		return jsonify({'process_name': process_name})

	return jsonify({'process_name': None})


@bp.route('/upgrade/run', methods=('GET', 'POST'))
@login_required
def run_upgrade():
	file_path = current_app.config.get('RULE_UPDATE_FILE')
	os.system(file_path)

	return jsonify({'result': 'success'})


@bp.route('/upgrade/create', methods=('GET', 'POST'))
@login_required
def create_upgrade():
	upgrade_setting = None

	upgrade_setting = save_upgrade(upgrade_setting, request)

	return render_template('setting/upgrade.html', upgrade_setting=upgrade_setting)


@bp.route('/upgrade/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update_upgrade(id):
	upgrade_setting = Upgrade.query.filter_by(id=id).first()

	upgrade_setting = save_upgrade(upgrade_setting, request)

	return render_template('setting/upgrade.html', upgrade_setting=upgrade_setting)


@bp.route('/upgrade')
@login_required
def upgrade():
	upgrade_setting = Upgrade.query.first()
	return render_template('setting/upgrade.html', upgrade_setting=upgrade_setting)



@bp.route('/warning')

app/templates/setting/backup.html
{% extends 'base.html' %}
{% block content %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">数据备份设置</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        {% if backup_setting %}
            <form action="{{ url_for('setting.update_backup', id=backup_setting.id) }}" class="form-horizontal"
                  method="post">
        {% else %}
            <form action="{{ url_for('setting.create_backup') }}" class="form-horizontal" method="post">
        {% endif %}
        <div class="box-body">
            <div class="form-group">
                <label class="col-sm-2 control-label">每隔</label>
                <select class="col-sm-5" name="step" id="step" value="40">
                    <option value="10"
                            {% if backup_setting and backup_setting.step == 10 %}selected="selected"{% endif %}>10天
                    </option>
                    <option value="20"
                            {% if backup_setting and backup_setting.step == 20 %}selected="selected"{% endif %}>20天
                    </option>
                    <option value="30"
                            {% if backup_setting and backup_setting.step == 30 %}selected="selected"{% endif %}>30天
                    </option>
                </select>
                <label class="col-sm-2 control-label">备份一次数据</label>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <a href="{{ url_for('log.index') }}">
                <button type="button" class="btn btn-default">取消</button>
            </a>
            <button type="submit" class="btn btn-info pull-right">保存</button>
        </div>
        <!-- /.box-footer -->
        </form>
    </div>

{% endblock %}

app/templates/setting/network.html
{% extends 'base.html' %}
{% block script %}
    <script>
        $(document).ready(function () {
            //Redirect to homepage
            $('#cancel').click(function () {
                window.location.href = "{{ url_for('log.index') }}";
            })
        });
    </script>
{% endblock %}
{% block content %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">网络设置</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        {% if network_setting %}
            <form role="form" action="{{ url_for('setting.update_network', id=network_setting.id) }}"
                  method="post">
        {% else %}
            <form role="form" action="{{ url_for('setting.create_network') }}" method="post">
        {% endif %}

        <div class="box-body">
            <!-- IP mask -->
            <div class="form-group">
                <label>监听网段_外网:</label>

                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <input name="extranet_segment" type="text" class="form-control"
                           data-inputmask="'alias': 'ip'" data-mask
                           {% if network_setting %}value={{ network_setting.extranet_segment }}{% endif %}>
                </div>
                <!-- /.input group -->
            </div>

            <div class="form-group">
                <label>监听网段_内网:</label>

                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <input name="intranet_segment" type="text" class="form-control"
                           data-inputmask="'alias': 'ip'" data-mask
                           {% if network_setting %}value={{ network_setting.intranet_segment }}{% endif %}>
                </div>
                <!-- /.input group -->
            </div>

            <div class="form-group">
                <label>监听网卡_外网:</label>

                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <input name="extranet_card" type="text" class="form-control"
                           data-inputmask="'alias': 'ip'" data-mask
                           {% if network_setting %}value={{ network_setting.extranet_card }}{% endif %}>
                </div>
                <!-- /.input group -->
            </div>

            <div class="form-group">
                <label>监听网卡_内网:</label>

                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <input name="intranet_card" type="text" class="form-control"
                           data-inputmask="'alias': 'ip'" data-mask
                           {% if network_setting %}value={{ network_setting.intranet_card }}{% endif %}>
                </div>
                <!-- /.input group -->
            </div>

        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button id="cancel" type="button" class="btn btn-default">取消</button>
            <button type="submit" class="btn btn-info pull-right">保存</button>
        </div>
        <!-- /.box-footer -->
        </form>
    </div>

{% endblock %}

app/templates/setting/upgrade.html
{% extends 'base.html' %}
{% block link %}
    <!-- Bootstrap time Picker -->
    <link rel="stylesheet"
          href="{{ url_for('static', filename='AdminLTE-2.4.5/plugins/timepicker/bootstrap-timepicker.min.css') }}">
{% endblock %}
{% block script %}
    <!-- bootstrap time picker -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/plugins/timepicker/bootstrap-timepicker.min.js') }}"></script>
    <!-- InputMask -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/plugins/input-mask/jquery.inputmask.js') }}"></script>
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.timepicker').timepicker({
                showInputs: false,
                defaultTime: '3:00',
                showMeridian: false,
            });
            //Money Euro
            $('[data-mask]').inputmask();
            //Redirect to homepage
            $('#cancel').click(function () {
                window.location.href = "{{ url_for('log.index') }}";
            })
        });
    </script>
{% endblock %}
{% block content %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">更新设置</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        {% if upgrade_setting %}
            <form role="form" action="{{ url_for('setting.update_upgrade', id=upgrade_setting.id) }}"
                  method="post">
        {% else %}
            <form role="form" action="{{ url_for('setting.create_upgrade') }}" method="post">
        {% endif %}

        <div class="box-body">
            <!-- IP mask -->
            <div class="form-group">
                <label>规则库更新地址:</label>

                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <input name="rule_upload_address" type="text" class="form-control"
                           data-inputmask="'alias': 'ip'" data-mask
                           {% if upgrade_setting %}value={{ upgrade_setting.rule_upload_address }}{% endif %}>
                </div>
                <!-- /.input group -->
            </div>
            <div class="bootstrap-timepicker">
                <div class="form-group">
                    <label>规则库自动更新时间:</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-clock-o"></i>
                        </div>
                        <input name="rule_upgrade_time" type="text" class="form-control timepicker"
                               {% if upgrade_setting %}value={{ upgrade_setting.rule_upgrade_time }}{% endif %}>
                    </div>
                    <!-- /.input group -->
                </div>
                <!-- /.form group -->
            </div>
            <div class="form-group">
                <label>威胁数据上传地址:</label>

                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-laptop"></i>
                    </div>
                    <input name="threat_upload_address" type="text" class="form-control"
                           data-inputmask="'alias': 'ip'" data-mask
                           {% if upgrade_setting %}value={{ upgrade_setting.threat_upload_address }}{% endif %}>
                </div>
                <!-- /.input group -->
            </div>
            <div class="bootstrap-timepicker">
                <div class="form-group">
                    <label>威胁情报自动上传时间:</label>

                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-clock-o"></i>
                        </div>
                        <input name="threat_upgrade_time" type="text" class="form-control timepicker"
                               {% if upgrade_setting %}value={{ upgrade_setting.threat_upgrade_time }}{% endif %}>
                    </div>
                    <!-- /.input group -->
                </div>
                <!-- /.form group -->
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button id="cancel" type="button" class="btn btn-default">取消</button>
            <button type="submit" class="btn btn-info pull-right">保存</button>
        </div>
        <!-- /.box-footer -->
        </form>
    </div>
{% endblock %}

app/templates/setting/warning.html
{% extends 'base.html' %}
{% block script %}
    <script>
        $(document).ready(function () {
            //Redirect to homepage
            $('#cancel').click(function () {
                window.location.href = "{{ url_for('log.index') }}";
            })
            //Add New Email
            $("#add_email").click(function () {
                $.post("{{ url_for('setting.create_email') }}",
                    {
                        email: $("#email").val()
                    },
                    function (data, status) {
                        window.location.reload();
                    });
            });
        });
    </script>
{% endblock %}
{% block content %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">报警设置</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        {% if warning_setting %}
            <form role="form" action="{{ url_for('setting.update_warning', id=warning_setting.id) }}"
                  method="post">
        {% else %}
            <form role="form" action="{{ url_for('setting.create_warning') }}" method="post">
        {% endif %}

        <div class="box-body">
            <!-- IP mask -->
            <div class="form-group">
                <label>警告级别:</label>
                <select class="form-control" name="level" id="level">
                    <option value="0" {% if warning_setting and warning_setting.level == 0 %}selected="selected"{% endif %}>1级
                    </option>
                    <option value="1" {% if warning_setting and warning_setting.level == 1 %}selected="selected"{% endif %}>2级
                    </option>
                    <option value="2" {% if warning_setting and warning_setting.level == 2 %}selected="selected"{% endif %}>3级
                    </option>
                    <option value="3" {% if warning_setting and warning_setting.level == 3 %}selected="selected"{% endif %}>4级
                    </option>
                    <option value="4" {% if warning_setting and warning_setting.level == 4 %}selected="selected"{% endif %}>5级
                    </option>
                    <option value="5" {% if warning_setting and warning_setting.level == 5 %}selected="selected"{% endif %}>6级
                    </option>
                </select>
            </div>

            <div class="form-group">
                <label>警告标题:</label>
                <input name="title" type="text" class="form-control" placeholder="Enter ..."
                       {% if warning_setting %}value={{ warning_setting.title }}{% endif %}>
            </div>

            <div class="form-group">
                <label>报警邮箱:</label>
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">邮箱列表</h3>
                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input id="email" type="text" name="email" class="form-control pull-right"
                                       placeholder="email ...">
                                <div class="input-group-btn">
                                    <button id="add_email" type="button" class="btn btn-default"><i
                                            class="fa fa-user-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <table class="table table-striped">
                            <tr>
                                <th style="width: 10px">#</th>
                                <th>邮箱</th>
                                <th style="width: 100px">操作</th>
                            </tr>
                            {% for email in emails %}
                                <tr>
                                    <td>{{ loop.index }}.</td>
                                    <td>{{ email.email }}</td>
                                    <td>
                                        <a class="action" href="{{ url_for('setting.delete_email', id=email.id) }}">
                                            <span class="label label-danger">删除</span>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button id="cancel" type="button" class="btn btn-default">取消</button>
                <button type="submit" class="btn btn-info pull-right">保存</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
{% endblock %}