app/main/views/auth.py
import functools

from flask import (
	Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash
from werkzeug.exceptions import abort

from ..models.auth import User
from ... import db
from sqlalchemy import or_


bp = Blueprint('auth', __name__, url_prefix='/auth')


def get_user(user_id, check_auth=True):
	user = User.query.filter_by(id=user_id).first()

	if user is None:
		abort(404, "User id {0} doesn't exist.".format(user_id))

	if check_auth and g.user.user_type != 1:
		abort(403)

	return user


def login_required(view):
	@functools.wraps(view)
	def wrapped_view(**kwargs):
		if g.user is None:
			return redirect(url_for('auth.login'))

		return view(**kwargs)

	return wrapped_view


@bp.before_app_request
def load_logged_in_user():
	user_id = session.get('user_id')

	if user_id is None:
		g.user = None
	else:
		g.user = User.query.filter_by(id=user_id).first()


@bp.route('/logout')
def logout():
	session.clear()
	return redirect(url_for('index'))


@bp.route('/login', methods=('GET', 'POST'))
def login():
	if request.method == 'POST':
		user_name = request.form['user_name']
		password = request.form['password']
		error = None

		user = User.query.filter_by(user_name=user_name).first()
		if user is None:
			error = 'Incorrect username.'
		elif not check_password_hash(user.password_hash, password):
			error = 'Incorrect password.'

		if error is None:
			session.clear()
			session['user_id'] = user.id
			return redirect(url_for('index'))

		flash(error)

	return render_template('auth/login.html')


@bp.route('/list')
def user_list():
	users = User.query.all()

	return render_template('auth/user_list.html', users=users)


@bp.route('/register', methods=('GET', 'POST'))
def register():
	if request.method == 'POST':
		user_name = request.form['user_name']
		email = request.form['email']
		password = request.form['password']

		error = None
		if not user_name:
			error = 'User name is required.'
		elif not email:
			error = 'email is required.'
		elif not password:
			error = 'Password is required.'
		elif User.query.filter(or_(User.user_name == user_name, User.email == email)).first() is not None:
			error = 'User {} or email {} is already registered.'.format(user_name, email)

		if error is None:
			user = User(user_name, email, password)
			db.session.add(user)
			db.session.commit()
			return redirect(url_for('auth.user_list'))

		flash(error)

	return render_template('auth/user.html')


@bp.route('/<int:id>/update', methods=('GET', 'POST'))
def update(id):
	user = get_user(id)

	if request.method == 'POST':
		user_name = request.form['user_name']
		email = request.form['email']
		status = request.form['status']

		error = None

		if not user_name:
			error = 'User name is required.'
		elif not email:
			error = 'email is required.'

		if error is None:
			user.user_name = user_name
			user.email = email
			user.status = status

			db.session.commit()

			return redirect(url_for('auth.user_list'))

		flash(error)

	return render_template('auth/user.html', user=user)


@bp.route('/<int:id>/update_password', methods=('GET', 'POST'))
def update_password(id):
	user = get_user(id)

	if request.method == 'POST':
		password = request.form['password']

		error = None

		if not password:
			error = 'password is required.'

		if error is None:
			user.password = password

			db.session.commit()

			return redirect(url_for('auth.user_list'))

		flash(error)

	return render_template('auth/user_password.html', user=user)


@bp.route('/<int:id>/delete', methods=('POST',))
def delete(id):
	user = get_user(id)

	db.session.delete(user)
	db.session.commit()

	return redirect(url_for('auth/list'))

app/main/views/log.py
from datetime import datetime, timedelta

from flask import (
	current_app, Blueprint, render_template
)

from ... import db
from .auth import login_required
from ..models.setting import Network, NetworkTypeEnum
from pyecharts import Line, Bar, Pie

import pandas
import json
import urllib.request


bp = Blueprint('log', __name__, url_prefix='/log')


def convert_ip_to_country(src):
	url = current_app.config.get('CONVERT_IP_URL').format(ip=src)
	response = urllib.request.urlopen(url)
	response = json.load(response)
	country = response['data']['country']

	return country


def build_df_top10_grouped_by_src_dst(df):
	country_column = []
	grouped_df = df.groupby(['src', 'dst']).agg({'msg': 'count'})\
		.sort_values(by='msg').tail(10)

	for (src, dst) in grouped_df.index:
		country_column.append(convert_ip_to_country(src))

	grouped_df['country'] = country_column
	return grouped_df


def convert_timestamp_to_hour(log):
	log_timestamp = log.timestamp
	# log_timestamp_hour = log_timestamp.strftime('%Y-%m-%d %H:00:00')
	log_timestamp_hour = log_timestamp.strftime('%H:00')

	return log_timestamp_hour


def convert_timestamp_to_day(log):
	log_timestamp = log.timestamp
	log_timestamp_day = log_timestamp.strftime('%Y-%m-%d')

	return log_timestamp_day


def load_24hour_log():
	query_sql = 'SELECT msg,dst,dstport,src,srcport,priority,timestamp FROM log'
	df = pandas.read_sql(query_sql, db.session.bind)

	start_time = datetime.now() + timedelta(hours=-24)
	df = df[df.timestamp > start_time]

	if not df.empty:
		df['timestamp_hour'] = df.apply(convert_timestamp_to_hour, axis=1)

	return df


def mark_dst_network_type(log, intranet_segment):
	network_type = NetworkTypeEnum.intranet if (log.dst.find(intranet_segment) == 0) else NetworkTypeEnum.extranet

	return network_type


def load_7day_log():
	query_sql = 'SELECT msg,dst,dstport,src,srcport,priority,timestamp FROM log'
	df = pandas.read_sql(query_sql, db.session.bind)

	start_time = datetime.now() + timedelta(days=-7)
	df = df[df.timestamp > start_time]

	if not df.empty:
		df['timestamp_day'] = df.apply(convert_timestamp_to_day, axis=1)

		network_setting = Network.query.first()
		df['network_type'] = df.apply(mark_dst_network_type, axis=1, args=(network_setting.intranet_segment,))

	return df


def build_top10_risk_diagram(df, logs):
	df_empty = None
	df_top10_high_risk_grouped_by_hour = None
	df_top10_low_risk_grouped_by_hour = None

	if not df.empty:
		df_top10_high_risk_grouped_by_hour = df[df.priority.isin([0, 1])].groupby('timestamp_hour').agg({'msg': 'count'}).sort_values(by='msg').tail(10)
		df_top10_low_risk_grouped_by_hour = df[df.priority == 2].groupby('timestamp_hour').agg({'msg': 'count'}).sort_values(by='msg').tail(10)

		start_time = datetime.now() + timedelta(hours=-24)
		dates = [(start_time + timedelta(hours=i)).strftime('%H:00') for i in range(0, 24)]
		# dates = [(start_time + timedelta(hours=i)).strftime('%Y-%m-%d %H:00:00') for i in range(0, 23)]
		df_empty = pandas.DataFrame({'timestamp_hour': dates, 'msg': 0})
		df_top10_high_risk_grouped_by_hour = pandas.merge(df_empty, df_top10_high_risk_grouped_by_hour, how='left', on='timestamp_hour')
		df_top10_high_risk_grouped_by_hour = df_top10_high_risk_grouped_by_hour.fillna(value=0)
		df_top10_low_risk_grouped_by_hour = pandas.merge(df_empty, df_top10_low_risk_grouped_by_hour, how='left', on='timestamp_hour')
		df_top10_low_risk_grouped_by_hour = df_top10_low_risk_grouped_by_hour.fillna(value=0)

	attr = list(df_empty['timestamp_hour']) if df_empty is not None else {}
	v1 = list(df_top10_high_risk_grouped_by_hour['msg_y']) if df_top10_high_risk_grouped_by_hour is not None else {}
	v2 = list(df_top10_low_risk_grouped_by_hour['msg_y']) if df_top10_low_risk_grouped_by_hour is not None else {}

	line = Line()
	line.add("高威胁", attr, v1)
	line.add("中低威胁", attr, v2)
	logs.update(top10_risk_diagram=line.render_embed())
	logs.update(echart_line_script_list=line.get_js_dependencies())


def build_top10_dst_diagram(df, logs):
	df_top10_grouped_by_dst = None

	if not df.empty:
		df_top10_grouped_by_dst = df.groupby('dst').agg({'msg': 'count'})\
			.sort_values(by='msg').tail(10)

	attr = list(df_top10_grouped_by_dst.index) if df_top10_grouped_by_dst is not None else {}
	v = list(df_top10_grouped_by_dst['msg']) if df_top10_grouped_by_dst is not None else {}
	bar = Bar()
	bar.add("DST", attr, v)

	logs.update(top10_dst_diagram=bar.render_embed())
	logs.update(echart_bar_script_list=bar.get_js_dependencies())

def build_top10_dst_port_diagram(df, logs):
	df_top10_grouped_by_dst_port = None

	if not df.empty:
		df_top10_grouped_by_dst_port = df.groupby('dstport').agg({'msg': 'count'})\
			.sort_values(by='msg').tail(10)

	attr = list(df_top10_grouped_by_dst_port.index) if df_top10_grouped_by_dst_port is not None else {}
	v = list(df_top10_grouped_by_dst_port['msg']) if df_top10_grouped_by_dst_port is not None else {}
	pie = Pie()
	pie.add("DST Port", attr, v)

	logs.update(top10_dst_port_diagram=pie.render_embed())
	logs.update(echart_pie_script_list=pie.get_js_dependencies())


def build_count_perday(df, logs):
	df_empty = None
	df_count_perday = None

	if not df.empty:
		df_count_perday = df.groupby('timestamp_day').agg({'msg': 'count'}).sort_values(by='msg').tail(10)
		start_day = datetime.now() + timedelta(days=-7)
		dates = [(start_day + timedelta(days=i)).strftime('%Y-%m-%d') for i in range(0, 7)]
		df_empty = pandas.DataFrame({'timestamp_day': dates, 'msg': 0})
		df_count_perday = pandas.merge(df_empty, df_count_perday, how='left', on='timestamp_day')
		df_count_perday = df_count_perday.fillna(value=0)

	attr = list(df_empty['timestamp_day']) if df_empty is not None else {}
	v = list(df_count_perday['msg_y']) if df_count_perday is not None else {}

	line = Line()
	line.add("威胁检测", attr, v)

	logs.update(count_perday=line.render_embed())
	logs.update(echart_line_script_list=line.get_js_dependencies())


@bp.route('/')
@login_required
def index():
	df = load_24hour_log()

	logs = {}
	# if not df.empty:
	logs.update(echart_host='https://pyecharts.github.io/assets/js')

	# The count of msg containing the word of 'DOS'
	df_dos_count = df[df.msg.str.contains("DOS")].agg({'msg': 'count'})['msg']
	logs.update(df_DOS_count=df_dos_count)

	# The count of msg containing the word of 'CnC'
	df_cnc_count = df[df.msg.str.contains("CnC")].agg({'msg': 'count'})['msg']
	logs.update(df_CnC_count=df_cnc_count)

	# The count of msg containing the word of 'Malware'
	df_malware_count = df[df.msg.str.contains("Malware")].agg({'msg': 'count'})['msg']
	logs.update(df_Malware_count=df_malware_count)

	# Top 10 count of per-hour logs with priority is 0 or 1
	df_high_risk_count = df[df.priority.isin([0, 1])].agg({'msg': 'count'})['msg']
	logs.update(df_high_risk_count=df_high_risk_count)

	# Top 10 count of per-hour logs with priority is 0 or 1
	build_top10_risk_diagram(df, logs)

	# Top 10 count of DST
	build_top10_dst_diagram(df, logs)

	# Top 10 count of DST Port
	build_top10_dst_port_diagram(df, logs)

	# Top 10 count of SRC & DST
	df_top10_grouped_by_src_dst = build_df_top10_grouped_by_src_dst(df)
	logs.update(df_top10_grouped_by_src_dst=df_top10_grouped_by_src_dst)

	return render_template('log/index.html', logs=logs)


@bp.route('/threat')
@login_required
def threat():
	df = load_7day_log()

	logs = {}
	if not df.empty:
		logs.update(echart_host='https://pyecharts.github.io/assets/js')

		# The count of logs per-day
		build_count_perday(df, logs)

		# The latest 10 logs
		df_latest_10 = df.sort_values(by='timestamp_day').tail(10)
		logs.update(df_latest_10=df_latest_10)

		# The extranet threat statics
		df_extranet_high_threat = df[(df.network_type == NetworkTypeEnum.extranet) & (df.priority.isin([0, 1]))]\
		    .groupby('dst').agg({'msg': 'count'})
		df_extranet_low_threat = df[(df.network_type == NetworkTypeEnum.extranet) & (df.priority == 2)]\
		    .groupby('dst').agg({'msg': 'count'})
		df_extranet_threat = pandas.merge(df_extranet_high_threat, df_extranet_low_threat, how='outer', on=['dst'])
		df_extranet_threat = df_extranet_threat.fillna(value=0)
		df_extranet_threat['sum'] = df_extranet_threat.apply(lambda x: x.msg_x + x.msg_y, axis=1)
		df_extranet_threat.sort_values(by='sum').tail(5)
		logs.update(df_extranet_threat=df_extranet_threat)

		# The intranet threat statics
		df_intranet_high_threat = df[(df.network_type == NetworkTypeEnum.intranet) & (df.priority.isin([0, 1]))]\
			.groupby('dst').agg({'msg': 'count'})
		df_intranet_low_threat = df[(df.network_type == NetworkTypeEnum.intranet) & (df.priority == 2)]\
			.groupby('dst').agg({'msg': 'count'})
		df_intranet_threat = pandas.merge(df_intranet_high_threat, df_intranet_low_threat, how='outer', on=['dst'])
		df_intranet_threat = df_intranet_threat.fillna(value=0)
		df_intranet_threat['sum'] = df_intranet_threat.apply(lambda x: x.msg_x + x.msg_y, axis=1)
		df_intranet_threat.sort_values(by='sum').tail(5)
		logs.update(df_intranet_threat=df_intranet_threat)

	return render_template('log/threat.html', logs=logs)

app/templates/base-1.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1>Flaskr</h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet"
          href="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/font-awesome/css/font-awesome.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet"
          href="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/Ionicons/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ url_for('static', filename='AdminLTE-2.4.5/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ url_for('static', filename='AdminLTE-2.4.5/dist/css/skins/_all-skins.min.css') }}">

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- jQuery 3 -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- SlimScroll -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/bower_components/fastclick/lib/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/dist/js/adminlte.min.js') }}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{ url_for('static', filename='AdminLTE-2.4.5/dist/js/demo.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.sidebar-menu li:not(.treeview) > a').on('click', function () {
                var $parent = $(this).parent().addClass('active');
                $parent.siblings('.treeview.active').find('> a').trigger('click');
                $parent.siblings().removeClass('active').find('li').removeClass('active');
            });
            $(window).on('load', function () {
                $('.sidebar-menu a').each(function () {
                    var cur = window.location.href;
                    var url = this.href;
                    if (cur.match(url)) {
                        $(this).parent().addClass('active')
                            .closest('.treeview-menu').addClass('.menu-open')
                            .closest('.treeview').addClass('active');
                    }
                });
            });
        })
    </script>
    {% block link %}{% endblock %}
    {% block style %}{% endblock %}
    {% block script %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="../../stock/index2.html" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>B</b>eye</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Big</b>eye</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        {% if g.user %}
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="hidden-xs">{{ g.user.user_name }}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="{{ url_for('auth.logout') }}" class="btn btn-default btn-flat">
                                            退出</a>
                                    </div>
                                </li>
                            </ul>
                        {% else %}
                            <a href="{{ url_for('auth.login') }}" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="hidden-xs">登录</span>
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>
                <li>
                    <a href={{ url_for('log.index') }}>
                        <i class="fa fa-dashboard"></i> <span>系统监控</span>
                    </a>
                </li>
                <li>
                    <a href={{ url_for('log.threat') }}>
                        <i class="fa fa-pie-chart"></i>
                        <span>威胁报告</span>
                    </a>
                </li>
                <li>
                    <a href={{ url_for('setting.process') }}>
                        <i class="fa fa-pie-chart"></i>
                        <span>设备运行</span>
                    </a>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-laptop"></i>
                        <span>系统设置</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href={{ url_for('setting.backup') }}><i class="fa fa-circle-o"></i>
                            备份设置</a></li>
                        <li><a href={{ url_for('setting.warning') }}><i class="fa fa-circle-o"></i> 报警设置</a></li>
                        <li><a href={{ url_for('auth.user_list') }}><i class="fa fa-circle-o"></i> 用户设置</a></li>
                        <li><a href={{ url_for('setting.upgrade') }}><i class="fa fa-circle-o"></i> 更新设置</a></li>
                        <li><a href={{ url_for('setting.network') }}><i class="fa fa-circle-o"></i> 网络设置</a></li>
                    </ul>
                </li>
            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                网络安全威胁
                <small>情报分析系统</small>
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            {% for message in get_flashed_messages() %}
                <div class="flash">{{ message }}</div>
            {% endfor %}
            {% block content %}{% endblock %}
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0
        </div>
        <strong>Copyright &copy; 2017-2018 <a href="https://adminlte.io">上海艾芒信息科技有限公司</a>.</strong> All rights
        reserved.
    </footer>

</div>
<!-- ./wrapper -->
</body>
</html>